// Generated by rosidl_generator_cs from interactive_cleanup_msgs/msg/InteractiveCleanupMsg.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace interactive_cleanup_msgs 
	{
		namespace msg 
		{
			[System.Serializable]
			public class InteractiveCleanupMsg : RosMessage
			{
				public string message;
				public string detail;


				public InteractiveCleanupMsg()
				{
					this.message = "";
					this.detail = "";
				}

				public InteractiveCleanupMsg(string message, string detail)
				{
					this.message = message;
					this.detail = detail;
				}

				new public static string GetMessageType()
				{
					return "interactive_cleanup_msgs/msg/InteractiveCleanupMsg";
				}

			} // class InteractiveCleanupMsg
		} // namespace msg
	} // namespace interactive_cleanup_msgs
} // namespace SIGVerse.RosBridge
